version: "3"
services:
  mongo: 
    image: mongo 
    ports: 
      - "27017:27017" 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "root" 
      MONGO_INITDB_ROOT_PASSWORD: "root" 
      MONGO_INITDB_DATABASE: "monsters" 
    networks: 
      - mongonet
    
  mongoclient: 
    image: mongoclient/mongoclient 
    ports: 
      - "8081:3000" 
    depends_on: 
      - mongo 
    environment: 
      STARTUP_DELAY: 10 
      MONGO_URL: "mongodb://root:root@mongo:27017/admin" 
    networks: 
      - mongonet


networks:
  mongonet: